# Generated by Django 2.2 on 2024-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartselection',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
