# Generated by Django 2.2 on 2024-12-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartselection_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartselection',
            name='img',
            field=models.CharField(default='https://media.istockphoto.com/id/609811304/photo/south-indian-food-uttapam-or-ooththappam-or-uthappa.jpg?s=612x612&w=0&k=20&c=mkFfxwamPGrcXHfPM8V_pA7EBs1SXNS7YvXBdFO_0xo=', max_length=1000),
            preserve_default=False,
        ),
    ]
